// components/LeavePeriodInput.tsx

import React from 'react';

interface LeavePeriodInputProps {
  startDate: string;
  endDate: string;
  onStartDateChange: (value: string) => void;
  onEndDateChange: (value: string) => void;
}

export const LeavePeriodInput: React.FC<LeavePeriodInputProps> = ({
  startDate,
  endDate,
  onStartDateChange,
  onEndDateChange,
}) => {
  const handleStartDateChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    onStartDateChange(event.target.value);
  };

  const handleEndDateChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    onEndDateChange(event.target.value);
  };
  
  const today = new Date().toISOString().split('T')[0];

  return (
    <div className="space-y-6">
      <div>
        <label htmlFor="leaveStartDate" className="block text-lg font-semibold text-slate-700">
          育児休業開始日
        </label>
        <input
          type="date"
          name="leaveStartDate"
          id="leaveStartDate"
          value={startDate}
          onChange={handleStartDateChange}
          className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-base border-slate-300 rounded-md py-3 px-4"
          min={today} // Optional: prevent past dates for start
        />
      </div>
      <div>
        <label htmlFor="leaveEndDate" className="block text-lg font-semibold text-slate-700">
          育児休業終了日
        </label>
        <input
          type="date"
          name="leaveEndDate"
          id="leaveEndDate"
          value={endDate}
          onChange={handleEndDateChange}
          className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-base border-slate-300 rounded-md py-3 px-4"
          min={startDate || today} // End date must be after start date
        />
      </div>
      <p className="mt-2 text-sm text-slate-500">
        育児休業を取得する期間を入力してください。
      </p>
    </div>
  );
};

// src/components/LeavePeriodInput.vue
<template>
  <div class="form-section">
    <div class="form-group">
      <label for="leaveStartDate">育児休業開始日</label>
      <input
        type="date"
        id="leaveStartDate"
        :value="startDate"
        @input="handleStartDateChange"
        :min="today"
      />
    </div>
    <div class="form-group">
      <label for="leaveEndDate">育児休業終了日</label>
      <input
        type="date"
        id="leaveEndDate"
        :value="endDate"
        @input="handleEndDateChange"
        :min="startDate || today"
      />
    </div>
    <p style="margin-top: 0.5rem; font-size: 0.875rem; color: #64748b;">
      育児休業を取得する期間を入力してください。
    </p>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

interface Props {
  startDate: string
  endDate: string
}

interface Emits {
  (e: 'update:startDate', value: string): void
  (e: 'update:endDate', value: string): void
}

const props = defineProps<Props>()
const emit = defineEmits<Emits>()

const today = computed(() => new Date().toISOString().split('T')[0])

const handleStartDateChange = (event: Event) => {
  const target = event.target as HTMLInputElement
  emit('update:startDate', target.value)
}

const handleEndDateChange = (event: Event) => {
  const target = event.target as HTMLInputElement
  emit('update:endDate', target.value)
}
</script>
