// components/MonthlySalariesInput.tsx
import React, { useMemo } from 'react';

interface MonthlySalariesInputProps {
  leaveStartDateString: string;
  monthlySalaries: string[];
  onChange: (index: number, value: string) => void;
}

const MONTHS_COUNT = 6;

// Helper function to get previous months' labels
export function getPreviousMonthLabels(leaveStartDateStr: string, count: number): { year: number, monthIndex: number, label: string }[] {
  if (!leaveStartDateStr) {
    // Create dummy labels if date is not set, to avoid errors during initial render if date is briefly invalid
    return Array(count).fill(null).map((_, i) => ({
        year: 0,
        monthIndex: 0,
        label: `Month ${count - i}`
    }));
  }
  
  const startDate = new Date(leaveStartDateStr);
  // Ensure we are working with a valid date object
  if (isNaN(startDate.getTime())) {
    return Array(count).fill(null).map((_, i) => ({
        year: 0,
        monthIndex: 0,
        label: `Month ${count - i} (Invalid Start Date)`
    }));
  }
  
  // Use the first day of the leave start month for consistent month arithmetic
  const firstDayOfLeaveStartMonth = new Date(startDate.getFullYear(), startDate.getMonth(), 1);
  
  const months = [];
  for (let i = 1; i <= count; i++) {
    const targetMonthDate = new Date(firstDayOfLeaveStartMonth);
    targetMonthDate.setMonth(firstDayOfLeaveStartMonth.getMonth() - i);
    const year = targetMonthDate.getFullYear();
    const monthIndex = targetMonthDate.getMonth(); // 0-indexed
    months.push({
      year,
      monthIndex,
      label: `${year}年${monthIndex + 1}月`,
    });
  }
  return months; // [Month-1, Month-2, ..., Month-6]
}


export const MonthlySalariesInput: React.FC<MonthlySalariesInputProps> = ({
  leaveStartDateString,
  monthlySalaries,
  onChange,
}) => {
  const monthLabels = useMemo(() => {
    return getPreviousMonthLabels(leaveStartDateString, MONTHS_COUNT);
  }, [leaveStartDateString]);

  const handleSalaryChange = (index: number, event: React.ChangeEvent<HTMLInputElement>) => {
    onChange(index, event.target.value);
  };

  return (
    <div className="space-y-4">
      <h3 className="text-lg font-semibold text-slate-700">
        育休開始前{MONTHS_COUNT}ヶ月間の各月給与（額面）
      </h3>
      <p className="text-sm text-slate-500">
        育児休業を開始する日を基点に、その直前の{MONTHS_COUNT}ヶ月間の各月の給与（税金や社会保険料が引かれる前の金額）を入力してください。
      </p>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-4">
        {monthLabels.map((month, index) => (
          <div key={index} className="space-y-1">
            <label htmlFor={`monthlySalary-${index}`} className="block text-sm font-medium text-slate-600">
              {month.label}の給与
            </label>
            <div className="mt-1 relative rounded-md shadow-sm">
              <input
                type="number"
                name={`monthlySalary-${index}`}
                id={`monthlySalary-${index}`}
                value={monthlySalaries[index]}
                onChange={(e) => handleSalaryChange(index, e)}
                className="focus:ring-indigo-500 focus:border-indigo-500 block w-full pr-12 sm:text-base border-slate-300 rounded-md py-2 px-3 placeholder-slate-400"
                placeholder="例: 300000"
                min="0"
                aria-describedby={`monthly-salary-currency-${index}`}
              />
              <div className="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                <span className="text-slate-500 sm:text-sm" id={`monthly-salary-currency-${index}`}>
                  円
                </span>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

// src/components/MonthlySalariesInput.vue
<template>
  <div class="form-section">
    <h3 style="font-size: 1.125rem; font-weight: 600; color: #334155; margin-bottom: 1rem;">
      育休開始前{{ MONTHS_COUNT }}ヶ月間の各月給与（額面）
    </h3>
    <p style="font-size: 0.875rem; color: #64748b; margin-bottom: 1rem;">
      育児休業を開始する日を基点に、その直前の{{ MONTHS_COUNT }}ヶ月間の各月の給与（税金や社会保険料が引かれる前の金額）を入力してください。
    </p>
    <div class="salary-grid">
      <div v-for="(month, index) in monthLabels" :key="index" class="form-group">
        <label :for="`monthlySalary-${index}`">
          {{ month.label }}の給与
        </label>
        <div class="salary-input-wrapper">
          <input
            type="number"
            :id="`monthlySalary-${index}`"
            :value="monthlySalaries[index]"
            @input="(event) => handleSalaryChange(index, event)"
            placeholder="例: 300000"
            min="0"
          />
          <span class="currency-symbol">円</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

interface Props {
  leaveStartDateString: string
  monthlySalaries: string[]
}

interface Emits {
  (e: 'update:salary', index: number, value: string): void
}

const props = defineProps<Props>()
const emit = defineEmits<Emits>()

const MONTHS_COUNT = 6

// Helper function to get previous months' labels
function getPreviousMonthLabels(leaveStartDateStr: string, count: number): { year: number, monthIndex: number, label: string }[] {
  if (!leaveStartDateStr) {
    return Array(count).fill(null).map((_, i) => ({
      year: 0,
      monthIndex: 0,
      label: `Month ${count - i}`
    }))
  }
  
  const startDate = new Date(leaveStartDateStr)
  if (isNaN(startDate.getTime())) {
    return Array(count).fill(null).map((_, i) => ({
      year: 0,
      monthIndex: 0,
      label: `Month ${count - i} (Invalid Start Date)`
    }))
  }
  
  const firstDayOfLeaveStartMonth = new Date(startDate.getFullYear(), startDate.getMonth(), 1)
  
  const months = []
  for (let i = 1; i <= count; i++) {
    const targetMonthDate = new Date(firstDayOfLeaveStartMonth)
    targetMonthDate.setMonth(firstDayOfLeaveStartMonth.getMonth() - i)
    const year = targetMonthDate.getFullYear()
    const monthIndex = targetMonthDate.getMonth()
    months.push({
      year,
      monthIndex,
      label: `${year}年${monthIndex + 1}月`,
    })
  }
  return months
}

const monthLabels = computed(() => {
  return getPreviousMonthLabels(props.leaveStartDateString, MONTHS_COUNT)
})

const handleSalaryChange = (index: number, event: Event) => {
  const target = event.target as HTMLInputElement
  emit('update:salary', index, target.value)
}
</script>

<style scoped lang="scss">
.salary-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 1rem;

  @media (min-width: 640px) {
    grid-template-columns: repeat(2, 1fr);
  }
}

.salary-input-wrapper {
  position: relative;
  
  input {
    padding-right: 2rem;
  }

  .currency-symbol {
    position: absolute;
    right: 0.75rem;
    top: 50%;
    transform: translateY(-50%);
    color: #64748b;
    font-size: 0.875rem;
    pointer-events: none;
  }
}
</style>
